openapi: "3.0.0"
info:
  version: "v3"
  title: "Federated Resource Query API Specification"
  description: >-
    "Federated Resource Query API is a web service for rare disease data sharing 
    that can be queried for information about specific rare disease data."
  contact:
    name: "EJP-RD Pillar 2 Query Builder Work Focus"
  #license:
    #name: "Apache 2.0"
    #url: "http://www.apache.org/licenses/LICENSE-2.0.html"
externalDocs:
  description: "EJP-RD Website"
  url: "https://www.ejprarediseases.org"
paths:
  /: 
    get:
      description: "Get information about the API."
      operationId: "getInformation"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoResponse"
        404:
          description: "not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /{versionNumber}/resource/search:
    get:
      description: "Get response to a query for a certain rare disease (resources)."
      operationId: "getResourceSearch"
      parameters:
        - name: code
          description: The rare disease code as full identifier.
          in: query
          required: true
          example: http://www.orpha.net/ORDO/Orphanet_730
          schema:
            type: array
            items:
              type: string
        - name: resourceType
          description: The type of resource the responded results are of, e.g. PatientRegistryDataset.
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
              enum: [PatientRegistryDataset, BiobankDataset, KnowledgeBase]
        - name: country
          description: The country in ISO 3166-1 alpha-2 format (e.g, IT, FR, NL)
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
              enum: [IT, FR, NL, ...]
        - name: name
          description: The name of the resource or a part of it
          in: query
          required: true
          schema:
            type: string
        - name: skip
          description: Number of pages to skip.
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: limit
          description: Size of the page.
          in: query
          required: false
          schema: 
            type: integer 
            format: int32
            default: 10
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DataResponse"
        400:
          description: Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but s/he is not granted for this resource)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: "not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    InfoResponse:
      type: object
      required:
        - name
        - apiVersions
        - resourceTypes
      properties:
        id:
          description: A primary identifier for the catalogue
          type: string
          example: "http://www.orpha.net"
        name:
          type: string
          description: A name for the catalogue
        description:
          type: string
          description: A description for the catalogue
        homepage:
          type: string
          description: The homepage of the catalogue
          example: "http://www.orpha.net"
        organisation:
          $ref: "#/components/schemas/Organisation"
        apiVersions:
          type: array
          description: Version of the API the catalogue is providing
          items:
            type: string
            enum:
              - v1
              - v2
              - v3
          example: [v2, v3]
        resourceTypes:
          type: "array"
          description: "List of resource types supported by this API."
          items:
            type: "string"
            enum:
              - "PatientRegistryDataset"
              - "BiobankDataset"
              - "KnowledgeBase"
          example: [
            "PatientRegistryDataset",
            "BiobankDataset"
          ]
        sampleRequests:
          type: array
          description: Examples of requests to the catalogue API.
          items:
            type: string
    ErrorResponse:
      type: "object"
      required: 
        - code 
        - message
      properties:
        code: 
          type: integer
          format: int32
        message: 
          type: string
    DataResponse:
      type: object
      required:
        - apiVersion
      properties:
        apiVersion:
          description: Version of the API. If specified, the value must match `apiVersion`
            in InfoResponse.
          type: string
          example: v0.2
        resourceResponses:
          description: The resource results.
          type: array
          items:
            $ref: "#/components/schemas/Resource"
        page:
          $ref: "#/components/schemas/Page"
    Resource:
      type: object
      required:
        - name
        - type
        - description
        - page
        - publisher
      properties:
        id:
          type: string
          description: The primary identifier of the resource in the catalogue
        name:
          type: string
          description: A name for the resource
          example: PDC registry
        type:
          type: string
          description: The type of the resource.
          example: "PatientRegistryDataset"
          enum:
            - PatientRegistryDataset
            - BiobankDataset
            - KnowledgeBase
        description:
          type: string
          description: A description for the resource
          example: PDC registry
        homepage:
          type: string
          description: The homepage of the resource
          example: "https://www.pcdregistry.eu/"
          format: url
        publisher:
          type: object
          description: The primary organisation responsible for publishing and maintaining the resource
          $ref: "#/components/schemas/Organisation"
        updated:
          type: string
          description: Time and date the resource was last updated.
          format: date-time
          example: 2021-01-31T16:33+00:00
    Organisation:
      description: A schema to describe an organisation
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: A name or short description for the organisation
          example: Orphanet
        description:
          type: string
          description: A description for the organiation
          example: Orphanet is a unique resource, gathering and improving knowledge on rare diseases
        homepage:
          type: string
          description: The primary URL for the homepage of the organisation
          format: url
          example: https://www.orpha.net/consor/cgi-bin/index.php
        location:
          description: Information about the location associated with the organisation
          $ref: "#/components/schemas/Location"
    Location:
      description: A schema to describe a location, region or jurisdiction
      type: object
      required:
        - code
        - title
      properties:
        code:
          description: The country in ISO 3166-1 alpha-2 format (e.g, IT, FR, NL)
          type: string
          enum: [IT, FR, NL, ...]
        title:
            description: The country name.
            type: string
    Page:
      type: object
      properties:
        totalNumbers:
          description: Total number of resources found
          type: integer
        totalPages:
          description: Total number of pages
        size:
          description: Number of resources for every page
          type: integer
        page:
          description: Number of the current page
          type: integer
