openapi: "3.0.0"
info:
  version: "0.2"
  title: "ERDRI.dor Query API Specification"
  description: >-
    "The ERDRI.dor query API is a web service for rare disease data sharing 
    that can be queried for information about specific rare disease data registries."
  #contact:
    #name: "Magic Mike"
    #email: "someone@erdri.dor"
  #license:
    #name: "Apache 2.0"
    #url: "http://www.apache.org/licenses/LICENSE-2.0.html"
externalDocs:
  description: "ERDRI.dor Website"
  url: "https://eu-rd-platform.jrc.ec.europa.eu/erdri-description_de"
paths:
  /: 
    get:
      description: "Get information about the API."
      operationId: "getInformation"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoResponse"
        404:
          description: "not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /resource:
    get:
      description: "Return a list of all listed resources in the catalogue."
      operationId: "getAllResources"
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DataResponse"
        400:
          description: Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but s/he is not granted for this resource)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: "not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /resource/search:
    get:
      description: "Get response to a query for a certain rare disease (resources)."
      operationId: "getResourceSearch"
      parameters:
        - name: name
          description: "Reference name of the disease. 
          Accepting strings on a certain naming convention basis."
          in: query
          required: false
          schema:
            type: string
        - name: orphaCode
          description: "The orphacode of the disease."
          in: query
          required: false
          schema:
            type: string
        - name: skip
          description: Number of pages to skip
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: limit
          description: Size of the page
          in: query
          required: false
          schema: 
            type: integer 
            format: int32
            default: 10
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DataResponse"
        400:
          description: Bad request (e.g. missing mandatory parameter)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: >-
            Unauthorised (e.g. when an unauthenticated user tries to access a
            protected resource)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        403:
          description: >-
            Forbidden (e.g. the resource is protected for all users or the user
            is authenticated but s/he is not granted for this resource)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: "not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          description: "unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    InfoResponse:
      type: object
      required:
        - id
        - type
      properties:
        id:
          description: A primary identifier for the catalogue
          type: string
          example: http://www.orpha.net"
        type:
          description: The primary type(s) for this catalogue
          type: array
          items:
            type: string
            enum: [CatalogOfRegistries, CatalogOfBiobanks]
          example: [CatalogOfRegistries]
        name:
          type: string
          description: A name for the catalogue
        description:
          type: string
          description: A description for the catalogue
        homepage:
          description: The homepage of the catalogue
          type: string
          example: http://www.orpha.net
        organization:
          $ref: "#/components/schemas/Organization"
        apiVersion:
          type: string
          description: Version of the API the catalogue is providing
          example: v0.1
        sampleRequests:
          description: >-
            Examples of interesting requests to the catalogue API.
          type: array
          items:
            type: string
    ErrorResponse:
      type: "object"
      required: 
        - code 
        - message
      properties:
        code: 
          type: integer
          format: int32
        message: 
          type: string
    DataResponse:
      type: object
      required:
        - apiVersion
      properties:
        apiVersion:
          description: Version of the API. If specified, the value must match `apiVersion`
            in InfoResponse.
          type: string
        resourceResponses:
          description: The resource results.
          type: array
          items:
            $ref: "#/components/schemas/Resource"
        page:
          $ref: "#/components/schemas/Page"
        error:
          $ref: "#/components/schemas/ErrorResponse"
    DataRequest:
      description: Request as interpreted by the API.
      type: object
      required:
        - orphaCode
      properties:
        orphaCode:
          description: "The orphacode of the disease."
          type: string
        referenceName:
          description: The reference name of the resource (disease name).
          type: string
        skip:
          description: Number of pages to skip
          type: integer
          format: int32
        limit:
          description: Size of the page
          type: integer 
          format: int32
          default: 10
    Resource:
      type: object
      required:
        - id
        - type
        - name
        - description
        - homepage
      properties:
        id:
          type: string
          description: A primary identifier for the resource
          example: https://www.pcdregistry.eu/
        name:
          type: string
          description: A name for the resource
          example: PDC registry
        description:
          type: string
          description: A description for the resource
          example: PDC registry
        homepage:
          type: string
          description: The homepage of the resource
          example: "https://www.pcdregistry.eu/"
          format: url
        publisher:
          type: object
          description: The primary organisation responsible for publishing and maintaining the resource
          $ref: "#/components/schemas/Organization"
        type:
          type: string
          description: The type of the resource.
          example: "Patient registry"
    Organization:
      description: A schema to describe an organisation
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: A primary identifier for the organisation
        name:
          type: string
          description: A name or short description for the organisation
          example: Orphanet
        description:
          type: string
          description: A description for the organiation
          example: Orphanet is a unique resource, gathering and improving knowledge on rare diseases
        homepage:
          type: string
          description: The primary URL for the homepage of the organisation
          format: url
          example: https://www.orpha.net/consor/cgi-bin/index.php
        location:
          description: Information about the location associated with the organisation
          $ref: "#/components/schemas/Location"
    Location:
      description: A schema to describe a location, region or jurisdiction
      type: object
      required:
        - id
        - country
      properties:
        id:
          description: A primary identifier for the location
          type: string
        city:
            description: The city of the location
            type: string
        country:
          description: The country the location is in
          type: string
        region:
          description: The region the location is in
          type: string
          enum: [international, europe]
    Page:
      type: object
      properties:
        totalNumbers:
          description: Total number of resources found
          type: integer
        totalPages:
          description: Total number of pages
        size:
          description: Number of resources for every page
          type: integer
        page:
          description: Number of the current page
          type: integer